### ISSUE TITLE
Converters for datasets into our format

### ISSUE THREAD

**Issue by riedelcastro** [uclmr/jack#2]
Implement loaders that save into the format of #1. To do:
- [x] FB15k (plus the FB15K-237 MSR version) #6 
- [x] MCTest
- [x] Squad #13 
- [x] Children Book Test
- [ ] AI2 Science Exam
- [x] ScienceQA #9 
- [ ] Stanford EE dataset
- [x] RTE datasets (SNLI?)
- [ ] TAC KBP #62
- [ ] bAbI 
- [ ] MovieQA (without the movies)
- [x] SimpleQuestions #22
- [ ] Arithmetic Word Problems #21 
- [ ] AI2 Animal Tensor #31
- [ ] Kinship #32 
- [ ] LAMBADA #34 
- [ ] Who did What cloze-style QA dataset #44 

(Add as you see fit).

Whoever is assigned (or assigns themselves) to one of these should create a new issue specific to that format.
