### ISSUE TITLE
Unsupervised training of context representations

### ISSUE THREAD

**Issue by rockt** [uclmr/jack#66]
Place for collecting TODOs for [autoread](https://github.com/dirkweissenborn/quebap) ICLR 2017
## TODOs
- [ ] Squad pointer network as downstream task
## Evaluation
- Main Downstream Tasks
  Experiment with small subsampled training data (pretrained vs w/o pretrained on sampled Wikipedia articles). Baseline: same model random initialized.
  - [ ] Q&A for WikiReading (what about DailyMail, CNN, CBT, LAMBADA, MCTest etc.?)
  - [ ] Squad
- Optional
  - [ ] SemEval-2007 Task 10 Lexical Substitution (LST-07)
  - [ ] LST-14 (Kremer et al., 2014)
  - [ ] Microsoft Sentence Completion Challenge (MSCC) (Zweig and Burges, 2011)
  - [ ] Supervised WSD Senseval-3 (SE-3)
  - [ ] Unsupervised POS tagging: http://www.cl.cam.ac.uk/~av308/UnsupEval.pdf
## Ideas
- [ ] Train on news corpora
- [ ] Train on simple wiki
- [ ] Sample between cloze-style and input noise cases during training
- [ ] Memory tape
- [ ] Curriculum learning, e.g., pretrain on simple wikipedia and then go to full wikipedia
## Done
- [x] saving and loading of pretrained autoreader model
- [x] switch to https://github.com/kudkudak/word-embeddings-benchmarks for word embeddings like word2vec and GloVe
